name: .NET

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: |
          3.1.x
          6.0.x
        
    - name: Restore dependencies
      run: dotnet ZooLab/ZooLab.sln restore
      
    - name: Build
      run: dotnet build ZooLab/ZooLab.sln --no-restore
      
    - name: Test
      run: dotnet test ZooLab/ZooLab.sln --no-build --verbosity normal --collect:"XPlat Code Coverage"

    - name: Codecov upload 
      uses: codecov/codecov-action@v3
